name = "SMSPool"
description = "Protect your identity today with our one-time use or rental phone numbers."
slug = "smspool"
hostnames = [ "www.smspool.net" ]
sources = [ "https://www.smspool.net/privacy-policy" ]
contributors = [ "smspool" ]

[rubric.behavioral-marketing]
value = "no"
citations = [
  "We collect and process the following personal data from visitors and subscribers. The purpose of this will be to register you as a User to our services: Username, and optionally email address. In addition, we may store the IP addresses from each visitor, which is only used for statistical purposes, and this will not be linked to your personal data."
]

[rubric.security]
value = "na"
notes = [
  "SMSPool does not store or require any personal data"
]

[rubric.third-party-collection]
value = "yes-specified-critical"
citations = [ "Smspool.net makes use of the services of third party companies that are processing your data. We are committed to only engage with those companies that fully comply with the GDPR and CCP, maintain the highest standards of data protection and never sell data to other parties. We only make use of the services of Cloudfare for Analytics, CDN and DDoS protection, based out of the United States that will monitor certain visitor behavior on our website. We advise you to read their Privacy Policy available on https://www.cloudflare.com/privacypolicy/. Next to Cloudflare; we use Stripe which processes your payments and the requests only contain your user ID." ]

[rubric.history]
value = "last-modified"

[rubric.data-deletion]
value = "yes-automated"
citations = [
  "\"Upon your request, Smspool.net will remove all personal data that we collected from you. Furthermore, each individual has the right to correct or update its personal information, deletions may take up to 48 hours to process.\""
]

[rubric.data-breaches]
value = "yes-72"
citations = [
  "\"In case of any breach, every user will be notified within 72 hours of the breach through any available channel that the user has provided.\""
]

[rubric.third-party-access]
value = "no"

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "\"We collect and process the following personal data from visitors and subscribers. The purpose of this will be to register you as a User to our services: Username, and optionally email address. In addition, we may store the IP addresses from each visitor, which is only used for statistical purposes, and this will not be linked to your personal data.\""
]

[rubric.noncritical-purposes]
value = "na"

[rubric.law-enforcement]
value = "reasonable"

[rubric.list-collected]
value = "na"

[rubric.revision-notify]
value = "na"