name = "SMSPool"
description = "Protect your identity today with our one-time use or rental phone numbers."
slug = "smspool"
hostnames = [ "www.smspool.net" ]
sources = [ "https://www.smspool.net/privacy-policy" ]
contributors = [ "smspool" ]

[rubric.behavioral-marketing]
value = "no"
citations = [
  "We collect and process the following personal data from visitors and subscribers. The purpose of this will be to register you as a User to our services: Username, and optionally email address. In addition, we may store the IP addresses from each visitor, which is only used for statistical purposes, and this will not be linked to your personal data."
]

[rubric.security]
value = "na"
notes = [
  "SMSPool does not store or require any personal data"
]

[rubric.third-party-collection]
value = "yes-specified-critical"
citations = [ "Smspool.net makes use of the services of third party companies that are processing your data. We are committed to only engage with those companies that fully comply with the GDPR and CCP, maintain the highest standards of data protection and never sell data to other parties. We only make use of the services of Cloudfare for Analytics, CDN and DDoS protection, based out of the United States that will monitor certain visitor behavior on our website. We advise you to read their Privacy Policy available on https://www.cloudflare.com/privacypolicy/. Next to Cloudflare; we use Stripe which processes your payments and the requests only contain your user ID." ]

[rubric.history]
value = "last-modified"

[rubric.data-deletion]
value = "yes-automated"
citations = [
  "\"Upon your request, Smspool.net will remove all personal data that we collected from you. Furthermore, each individual has the right to correct or update its personal information, deletions may take up to 48 hours to process.\""
]

[rubric.data-breaches]
value = "eventually"
citations = [
  "\"In an event of a breach, we recognize our responsibility to our customers and to the public to disclose the nature of the risk and provide a transparent account of the events without undue delay. We follow applicable requirements under the laws, that is, the Canadian data privacy breach notification requirements and the requirements related to data breach notification under the GDPR.\""
]

[rubric.third-party-access]
value = "yes-unspecified-critical"
citations = [
  "\"Your Secure and Service data are held by third party data processors, who provide us with hosting and other infrastructure services. The locations of these are described above. In many cases (but we cannot promise that this will always be the case) even Service data held by these entities is encrypted with keys held only by us.\"\n\n\"Data needed to process payments is collected by our payment processor, Stripe, Inc., which conforms to the U.S.-E.U. Privacy Shield Framework.\""
]

[rubric.data-collection-reasoning]
value = "yes"
citations = [
  "\"We retain only enough Service Data to operate and maintain the services. These data are never used for any other purpose.\""
]

[rubric.noncritical-purposes]
value = "opt-in"
citations = [
  "In some cases we seek diagnostic reports and other troubleshooting, bug, and crash reports from customers to help identify and solve problems with our products and services. This information is sent to us only on a case by case basis, or by users who explicitly opt into our beta software programs or who otherwise explicitly choose to provide diagnostic data to us."
]

[rubric.law-enforcement]
value = "reasonable"
citations = [
  "\"We will comply with applicable laws and the contracts with our customers to provide Service Data and encrypted Secure Data to law enforcement agencies. If permitted, we will notify you of such a request and whether or not we have complied.\""
]

[rubric.list-collected]
value = "generally"
citations = [
  "\"We get some limited data from your use of the 1Password products and services. Such data includes your IP address, and the make and model of your device through which you access or use 1Password products or services.\"\n\n\"It is visible to our staff and includes, but is not limited to, server logs, billing information, client IP addresses, number of vaults and number of items in vaults, company or family name, and email addresses. Service data includes the name you provide us for your profile and any image that you may upload, at your option and discretion, as part of your profile.\""
]

[rubric.revision-notify]
value = "yes"
citations = [
  "\"At our discretion, we may make changes to this Policy and note the date of the last revision. You should check here frequently if you need to know of updates to our Privacy Policy. We maintain the right to send you annoying email informing you of substantive changes. Previous versions will be made available from this page.\""
]
